services:
  - type: redis
    name: bronx-cache
    ipAllowList: [] # only allow internal connections
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: bronx-site
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: bronx-cache
          property: connectionString
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /avatar.png
        name: Cache-Control
        value: public, max-age=3600
      - path: /fonts/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /style.css
        name: Cache-Control
        value: public, max-age=3600
      - path: /script.js
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
